<?php


namespace Linh\Hotel\Model\ResourceModel\Hotel;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    public $_idFieldName = "hotel_id";
    protected function _construct()
    {
        $this->_init('Linh\Hotel\Model\Hotel','Linh\Hotel\Model\ResourceModel\Hotel');
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
