<span><strong>Location hotel:</strong></span>
<select id="loactionhotel" name="location_hotel">
    <?php foreach ($block->getLocationHotel() as $hotel): ?>
        <option value="<?php echo $hotel->getHotelId()?>"><?php echo $hotel->getLocationStreet() ?></option>
    <?php endforeach; ?>
</select>
<script>
    require(['jquery'],function ($){
        $('#loactionhotel').change(function (event) {
            event.preventDefault();
            let link_url = "http://m234.local/hotel/index/gethotelajax";
            let getHotelId = $('#loactionhotel').val();
            $.ajax({
                url : link_url,
                type: "POST",
                data: { hotel_id :getHotelId },
                dataType:'json',
                success : function (data)
                {
                   alert(data);
                });
        });
    });
</script>
